---
- hosts: all
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest

  - name: Copy nginx config
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - Start nginx

  handlers:
  - name: Start nginx
    systemd:
      name: nginx
      state: started
      enabled: true
      